# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"import_data": "00_core.ipynb",
         "preprocess_data": "00_core.ipynb",
         "Transformer_RBP": "00_core.ipynb",
         "build_input_layer": "00_core.ipynb",
         "build_keras_model": "00_core.ipynb",
         "main": "00_core.ipynb",
         "EPOCHS": "00_core.ipynb",
         "BATCH_SIZE": "00_core.ipynb",
         "LOWERCASE": "00_core.ipynb",
         "CLEAN": "00_core.ipynb",
         "REMOVE_CONTINUATIONS": "00_core.ipynb",
         "data_filepath": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://glicerico.github.io/SGNN/"

git_url = "https://github.com/glicerico/SGNN/tree/master/"

def custom_doc_links(name): return None
