# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"data_filepath": "00_core.ipynb",
         "data": "00_core.ipynb",
         "y": "00_core.ipynb",
         "X": "00_core.ipynb",
         "le": "00_core.ipynb",
         "y_train": "00_core.ipynb",
         "y_test": "00_core.ipynb",
         "char_ngram_range": "00_core.ipynb",
         "char_term_frequency_params": "00_core.ipynb",
         "T": "00_core.ipynb",
         "d": "00_core.ipynb",
         "rand_seeds": "00_core.ipynb",
         "hashing_feature_union_params": "00_core.ipynb",
         "MyRBP": "00_core.ipynb",
         "params": "00_core.ipynb",
         "preprocessor": "00_core.ipynb",
         "union_pipe": "00_core.ipynb",
         "train_labels": "00_core.ipynb",
         "test_labels": "00_core.ipynb",
         "train_features": "00_core.ipynb",
         "model": "00_core.ipynb",
         "lr_schedule": "00_core.ipynb",
         "opt": "00_core.ipynb",
         "EPOCHS": "00_core.ipynb",
         "BATCH_SIZE": "00_core.ipynb",
         "test_features": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://glicerico.github.io/SGNN/"

git_url = "https://github.com/glicerico/SGNN/tree/master/"

def custom_doc_links(name): return None
